name: Test Cases

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-pandoc@v2
      - run: Rscript applyBenefitsCalculator.R sample_a
      - run: Rscript applyBenefitsCalculator.R sample_b
      - run: Rscript applyBenefitsCalculator.R sample_c
      - name: "Print project csv output"
        run: |
          echo "sample_a:"
          cat output/results_sample_a.csv
          echo "sample_b:"
          cat output/results_sample_b.csv
          echo "sample_c:"
          cat output/results_sample_c.csv
      - name: Archive project output
        uses: actions/upload-artifact@v4
        with:
          name: project-output
          path: output


